// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVGJCuwwYKDzmo9ZZGhxCuaB2RPjxdrFQ',
    appId: '1:776767129937:web:95227ffe42f35fb3a76b70',
    messagingSenderId: '776767129937',
    projectId: 'quiero-jugar-41baa',
    authDomain: 'quiero-jugar-41baa.firebaseapp.com',
    storageBucket: 'quiero-jugar-41baa.appspot.com',
    measurementId: 'G-1GKH7J13TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO7fLwPm_CziBQGXrnihD3Jy3Z6yrvbzA',
    appId: '1:776767129937:android:18cfe9688e15f183a76b70',
    messagingSenderId: '776767129937',
    projectId: 'quiero-jugar-41baa',
    storageBucket: 'quiero-jugar-41baa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmsN2-FITmnSsfbRgjMiNtVTCXcXJyWz4',
    appId: '1:776767129937:ios:4425519401f15b5da76b70',
    messagingSenderId: '776767129937',
    projectId: 'quiero-jugar-41baa',
    storageBucket: 'quiero-jugar-41baa.appspot.com',
    iosClientId: '776767129937-0v7fs8g887ubhk8esf1trvq8rmjb7083.apps.googleusercontent.com',
    iosBundleId: 'com.example.quieroJugar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmsN2-FITmnSsfbRgjMiNtVTCXcXJyWz4',
    appId: '1:776767129937:ios:dbe038b78e16aa41a76b70',
    messagingSenderId: '776767129937',
    projectId: 'quiero-jugar-41baa',
    storageBucket: 'quiero-jugar-41baa.appspot.com',
    iosClientId: '776767129937-7o4cocfpgcmvepthj1dn77arr5pisgp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.quieroJugar.RunnerTests',
  );
}
